services:
  server:
    build: .
    volumes:
      - /home/thecrown/certs/haoyuanlord.com/privkey.pem:/app/cert/website.key
      - /home/thecrown/certs/haoyuanlord.com/fullchain.pem:/app/cert/website.crt
    ports:
      - "4443:443"